name: package

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/stuartleeks/tre-cli/tre-cli-devcontainer
          runCmd: make build-package
          push: never

      - name: Upload Wheel as artifact
        uses: actions/upload-artifact@v3
        with:
          name: tre-cli
          path: dist/tre-*.whl
